name: Games
version: '${project.version}'
main: com.etsuni.games.Games
api-version: 1.19
depend: [Vault]
commands:
  games:
    description: Opens Games Main Menu
  cf:
    description: Get to coinflip quickly
  rps:
    description: Get to rps quickly
  crash:
    description: Get to crash quickly
